version: '3'
services:
  spring-boot-app:
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: admin

  react-app:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "80:80"
      volumes:
        - ./frontend/.docker/nginx.conf:/etc/nginx/nginx.conf

